# Generated by Django 4.1.7 on 2023-03-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='order',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='restaurant.ingredient'),
        ),
    ]
